blank_issues_enabled: false
contact_links:
  - name: Help and Question
    url: https://github.com/vuejs/router/discussions/new?category=help-and-questions
    about: Ask a question or discuss about Vue Router
  - name: GitHub Sponsors
    url: https://github.com/sponsors/posva
    about: Like this project? Please consider supporting the author.
  - name: Open Collective
    url: https://opencollective.com/vuejs/donate
    about: Love Vue.js? Please consider supporting us via Open Collective.
