/**
 * @publicApi
 */
export enum HttpStatus {
  CONTINUE = 100, // 服务器已收到请求的初始部分，客户端应继续请求
  SWITCHING_PROTOCOLS = 101,// 
  PROCESSING = 102,// 服务器正在处理，但尚未完成
  EARLYHINTS = 103,// 
  OK = 200,// 请求成功，一般用于GET或POST请求
  CREATED = 201,// 已创建成功，一般用于POST请求
  ACCEPTED = 202,// 已接受请求，但尚未处理完成
  NON_AUTHORITATIVE_INFORMATION = 203,// 
  NO_CONTENT = 204,// 
  RESET_CONTENT = 205,// 
  PARTIAL_CONTENT = 206,// 
  AMBIGUOUS = 300,// 
  MOVED_PERMANENTLY = 301,// 
  FOUND = 302,// 
  SEE_OTHER = 303,// 
  NOT_MODIFIED = 304,// 
  TEMPORARY_REDIRECT = 307,// 
  PERMANENT_REDIRECT = 308,// 
  BAD_REQUEST = 400,// 
  UNAUTHORIZED = 401,// 
  PAYMENT_REQUIRED = 402,// 
  FORBIDDEN = 403,// 
  NOT_FOUND = 404,// 
  METHOD_NOT_ALLOWED = 405,// 
  NOT_ACCEPTABLE = 406,// 
  PROXY_AUTHENTICATION_REQUIRED = 407,// 
  REQUEST_TIMEOUT = 408,// 
  CONFLICT = 409,// 
  GONE = 410,// 
  LENGTH_REQUIRED = 411,// 
  PRECONDITION_FAILED = 412,// 
  PAYLOAD_TOO_LARGE = 413,// 
  URI_TOO_LONG = 414,// 
  UNSUPPORTED_MEDIA_TYPE = 415,// 
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,// 
  EXPECTATION_FAILED = 417,// 
  I_AM_A_TEAPOT = 418,// 
  MISDIRECTED = 421,// 
  UNPROCESSABLE_ENTITY = 422,// 
  FAILED_DEPENDENCY = 424,// 
  PRECONDITION_REQUIRED = 428,// 
  TOO_MANY_REQUESTS = 429,// 
  INTERNAL_SERVER_ERROR = 500,// 
  NOT_IMPLEMENTED = 501,// 
  BAD_GATEWAY = 502,// 
  SERVICE_UNAVAILABLE = 503,// 
  GATEWAY_TIMEOUT = 504,// 
  HTTP_VERSION_NOT_SUPPORTED = 505,// 
}
